// source: order_events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.ecommerce.orders.Customer', null, global);
goog.exportSymbol('proto.ecommerce.orders.EventType', null, global);
goog.exportSymbol('proto.ecommerce.orders.FailureReason', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderConfirmed', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderCreated', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderEvent', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderEvent.PayloadCase', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderFailed', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderItem', null, global);
goog.exportSymbol('proto.ecommerce.orders.OrderSummary', null, global);
goog.exportSymbol('proto.ecommerce.orders.PaymentProcessed', null, global);
goog.exportSymbol('proto.ecommerce.orders.PaymentResult', null, global);
goog.exportSymbol('proto.ecommerce.orders.PaymentStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ecommerce.orders.OrderEvent.oneofGroups_);
};
goog.inherits(proto.ecommerce.orders.OrderEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderEvent.displayName = 'proto.ecommerce.orders.OrderEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderCreated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ecommerce.orders.OrderCreated.repeatedFields_, null);
};
goog.inherits(proto.ecommerce.orders.OrderCreated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderCreated.displayName = 'proto.ecommerce.orders.OrderCreated';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.PaymentProcessed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.PaymentProcessed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.PaymentProcessed.displayName = 'proto.ecommerce.orders.PaymentProcessed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderConfirmed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.OrderConfirmed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderConfirmed.displayName = 'proto.ecommerce.orders.OrderConfirmed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderFailed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.OrderFailed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderFailed.displayName = 'proto.ecommerce.orders.OrderFailed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.Customer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.Customer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.Customer.displayName = 'proto.ecommerce.orders.Customer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.OrderItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderItem.displayName = 'proto.ecommerce.orders.OrderItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.PaymentResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.PaymentResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.PaymentResult.displayName = 'proto.ecommerce.orders.PaymentResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ecommerce.orders.OrderSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ecommerce.orders.OrderSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ecommerce.orders.OrderSummary.displayName = 'proto.ecommerce.orders.OrderSummary';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ecommerce.orders.OrderEvent.oneofGroups_ = [[5,6,7,8]];

/**
 * @enum {number}
 */
proto.ecommerce.orders.OrderEvent.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  ORDER_CREATED: 5,
  PAYMENT_PROCESSED: 6,
  ORDER_CONFIRMED: 7,
  ORDER_FAILED: 8
};

/**
 * @return {proto.ecommerce.orders.OrderEvent.PayloadCase}
 */
proto.ecommerce.orders.OrderEvent.prototype.getPayloadCase = function() {
  return /** @type {proto.ecommerce.orders.OrderEvent.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.ecommerce.orders.OrderEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
orderId: jspb.Message.getFieldWithDefault(msg, 2, ""),
eventType: jspb.Message.getFieldWithDefault(msg, 3, 0),
timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
orderCreated: (f = msg.getOrderCreated()) && proto.ecommerce.orders.OrderCreated.toObject(includeInstance, f),
paymentProcessed: (f = msg.getPaymentProcessed()) && proto.ecommerce.orders.PaymentProcessed.toObject(includeInstance, f),
orderConfirmed: (f = msg.getOrderConfirmed()) && proto.ecommerce.orders.OrderConfirmed.toObject(includeInstance, f),
orderFailed: (f = msg.getOrderFailed()) && proto.ecommerce.orders.OrderFailed.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderEvent}
 */
proto.ecommerce.orders.OrderEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderEvent;
  return proto.ecommerce.orders.OrderEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderEvent}
 */
proto.ecommerce.orders.OrderEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 3:
      var value = /** @type {!proto.ecommerce.orders.EventType} */ (reader.readEnum());
      msg.setEventType(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 5:
      var value = new proto.ecommerce.orders.OrderCreated;
      reader.readMessage(value,proto.ecommerce.orders.OrderCreated.deserializeBinaryFromReader);
      msg.setOrderCreated(value);
      break;
    case 6:
      var value = new proto.ecommerce.orders.PaymentProcessed;
      reader.readMessage(value,proto.ecommerce.orders.PaymentProcessed.deserializeBinaryFromReader);
      msg.setPaymentProcessed(value);
      break;
    case 7:
      var value = new proto.ecommerce.orders.OrderConfirmed;
      reader.readMessage(value,proto.ecommerce.orders.OrderConfirmed.deserializeBinaryFromReader);
      msg.setOrderConfirmed(value);
      break;
    case 8:
      var value = new proto.ecommerce.orders.OrderFailed;
      reader.readMessage(value,proto.ecommerce.orders.OrderFailed.deserializeBinaryFromReader);
      msg.setOrderFailed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEventType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOrderCreated();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.ecommerce.orders.OrderCreated.serializeBinaryToWriter
    );
  }
  f = message.getPaymentProcessed();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.ecommerce.orders.PaymentProcessed.serializeBinaryToWriter
    );
  }
  f = message.getOrderConfirmed();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.ecommerce.orders.OrderConfirmed.serializeBinaryToWriter
    );
  }
  f = message.getOrderFailed();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.ecommerce.orders.OrderFailed.serializeBinaryToWriter
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.OrderEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.setEventId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string order_id = 2;
 * @return {string}
 */
proto.ecommerce.orders.OrderEvent.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional EventType event_type = 3;
 * @return {!proto.ecommerce.orders.EventType}
 */
proto.ecommerce.orders.OrderEvent.prototype.getEventType = function() {
  return /** @type {!proto.ecommerce.orders.EventType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.ecommerce.orders.EventType} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.setEventType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ecommerce.orders.OrderEvent.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
*/
proto.ecommerce.orders.OrderEvent.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderEvent.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional OrderCreated order_created = 5;
 * @return {?proto.ecommerce.orders.OrderCreated}
 */
proto.ecommerce.orders.OrderEvent.prototype.getOrderCreated = function() {
  return /** @type{?proto.ecommerce.orders.OrderCreated} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.OrderCreated, 5));
};


/**
 * @param {?proto.ecommerce.orders.OrderCreated|undefined} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
*/
proto.ecommerce.orders.OrderEvent.prototype.setOrderCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.ecommerce.orders.OrderEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.clearOrderCreated = function() {
  return this.setOrderCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderEvent.prototype.hasOrderCreated = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional PaymentProcessed payment_processed = 6;
 * @return {?proto.ecommerce.orders.PaymentProcessed}
 */
proto.ecommerce.orders.OrderEvent.prototype.getPaymentProcessed = function() {
  return /** @type{?proto.ecommerce.orders.PaymentProcessed} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.PaymentProcessed, 6));
};


/**
 * @param {?proto.ecommerce.orders.PaymentProcessed|undefined} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
*/
proto.ecommerce.orders.OrderEvent.prototype.setPaymentProcessed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.ecommerce.orders.OrderEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.clearPaymentProcessed = function() {
  return this.setPaymentProcessed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderEvent.prototype.hasPaymentProcessed = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional OrderConfirmed order_confirmed = 7;
 * @return {?proto.ecommerce.orders.OrderConfirmed}
 */
proto.ecommerce.orders.OrderEvent.prototype.getOrderConfirmed = function() {
  return /** @type{?proto.ecommerce.orders.OrderConfirmed} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.OrderConfirmed, 7));
};


/**
 * @param {?proto.ecommerce.orders.OrderConfirmed|undefined} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
*/
proto.ecommerce.orders.OrderEvent.prototype.setOrderConfirmed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.ecommerce.orders.OrderEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.clearOrderConfirmed = function() {
  return this.setOrderConfirmed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderEvent.prototype.hasOrderConfirmed = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional OrderFailed order_failed = 8;
 * @return {?proto.ecommerce.orders.OrderFailed}
 */
proto.ecommerce.orders.OrderEvent.prototype.getOrderFailed = function() {
  return /** @type{?proto.ecommerce.orders.OrderFailed} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.OrderFailed, 8));
};


/**
 * @param {?proto.ecommerce.orders.OrderFailed|undefined} value
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
*/
proto.ecommerce.orders.OrderEvent.prototype.setOrderFailed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.ecommerce.orders.OrderEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderEvent} returns this
 */
proto.ecommerce.orders.OrderEvent.prototype.clearOrderFailed = function() {
  return this.setOrderFailed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderEvent.prototype.hasOrderFailed = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ecommerce.orders.OrderCreated.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderCreated.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderCreated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderCreated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderCreated.toObject = function(includeInstance, msg) {
  var f, obj = {
orderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
customer: (f = msg.getCustomer()) && proto.ecommerce.orders.Customer.toObject(includeInstance, f),
itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.ecommerce.orders.OrderItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderCreated}
 */
proto.ecommerce.orders.OrderCreated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderCreated;
  return proto.ecommerce.orders.OrderCreated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderCreated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderCreated}
 */
proto.ecommerce.orders.OrderCreated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 2:
      var value = new proto.ecommerce.orders.Customer;
      reader.readMessage(value,proto.ecommerce.orders.Customer.deserializeBinaryFromReader);
      msg.setCustomer(value);
      break;
    case 3:
      var value = new proto.ecommerce.orders.OrderItem;
      reader.readMessage(value,proto.ecommerce.orders.OrderItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderCreated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderCreated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderCreated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderCreated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCustomer();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ecommerce.orders.Customer.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ecommerce.orders.OrderItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string order_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.OrderCreated.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderCreated} returns this
 */
proto.ecommerce.orders.OrderCreated.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Customer customer = 2;
 * @return {?proto.ecommerce.orders.Customer}
 */
proto.ecommerce.orders.OrderCreated.prototype.getCustomer = function() {
  return /** @type{?proto.ecommerce.orders.Customer} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.Customer, 2));
};


/**
 * @param {?proto.ecommerce.orders.Customer|undefined} value
 * @return {!proto.ecommerce.orders.OrderCreated} returns this
*/
proto.ecommerce.orders.OrderCreated.prototype.setCustomer = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderCreated} returns this
 */
proto.ecommerce.orders.OrderCreated.prototype.clearCustomer = function() {
  return this.setCustomer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderCreated.prototype.hasCustomer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated OrderItem items = 3;
 * @return {!Array<!proto.ecommerce.orders.OrderItem>}
 */
proto.ecommerce.orders.OrderCreated.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.ecommerce.orders.OrderItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ecommerce.orders.OrderItem, 3));
};


/**
 * @param {!Array<!proto.ecommerce.orders.OrderItem>} value
 * @return {!proto.ecommerce.orders.OrderCreated} returns this
*/
proto.ecommerce.orders.OrderCreated.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ecommerce.orders.OrderItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ecommerce.orders.OrderItem}
 */
proto.ecommerce.orders.OrderCreated.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ecommerce.orders.OrderItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ecommerce.orders.OrderCreated} returns this
 */
proto.ecommerce.orders.OrderCreated.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.PaymentProcessed.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.PaymentProcessed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.PaymentProcessed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.PaymentProcessed.toObject = function(includeInstance, msg) {
  var f, obj = {
orderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
paymentResult: (f = msg.getPaymentResult()) && proto.ecommerce.orders.PaymentResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.PaymentProcessed}
 */
proto.ecommerce.orders.PaymentProcessed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.PaymentProcessed;
  return proto.ecommerce.orders.PaymentProcessed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.PaymentProcessed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.PaymentProcessed}
 */
proto.ecommerce.orders.PaymentProcessed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 2:
      var value = new proto.ecommerce.orders.PaymentResult;
      reader.readMessage(value,proto.ecommerce.orders.PaymentResult.deserializeBinaryFromReader);
      msg.setPaymentResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.PaymentProcessed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.PaymentProcessed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.PaymentProcessed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.PaymentProcessed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPaymentResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ecommerce.orders.PaymentResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional string order_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.PaymentProcessed.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.PaymentProcessed} returns this
 */
proto.ecommerce.orders.PaymentProcessed.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional PaymentResult payment_result = 2;
 * @return {?proto.ecommerce.orders.PaymentResult}
 */
proto.ecommerce.orders.PaymentProcessed.prototype.getPaymentResult = function() {
  return /** @type{?proto.ecommerce.orders.PaymentResult} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.PaymentResult, 2));
};


/**
 * @param {?proto.ecommerce.orders.PaymentResult|undefined} value
 * @return {!proto.ecommerce.orders.PaymentProcessed} returns this
*/
proto.ecommerce.orders.PaymentProcessed.prototype.setPaymentResult = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.PaymentProcessed} returns this
 */
proto.ecommerce.orders.PaymentProcessed.prototype.clearPaymentResult = function() {
  return this.setPaymentResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.PaymentProcessed.prototype.hasPaymentResult = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderConfirmed.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderConfirmed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderConfirmed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderConfirmed.toObject = function(includeInstance, msg) {
  var f, obj = {
orderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
summary: (f = msg.getSummary()) && proto.ecommerce.orders.OrderSummary.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderConfirmed}
 */
proto.ecommerce.orders.OrderConfirmed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderConfirmed;
  return proto.ecommerce.orders.OrderConfirmed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderConfirmed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderConfirmed}
 */
proto.ecommerce.orders.OrderConfirmed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 2:
      var value = new proto.ecommerce.orders.OrderSummary;
      reader.readMessage(value,proto.ecommerce.orders.OrderSummary.deserializeBinaryFromReader);
      msg.setSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderConfirmed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderConfirmed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderConfirmed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderConfirmed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSummary();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ecommerce.orders.OrderSummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional string order_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.OrderConfirmed.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderConfirmed} returns this
 */
proto.ecommerce.orders.OrderConfirmed.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional OrderSummary summary = 2;
 * @return {?proto.ecommerce.orders.OrderSummary}
 */
proto.ecommerce.orders.OrderConfirmed.prototype.getSummary = function() {
  return /** @type{?proto.ecommerce.orders.OrderSummary} */ (
    jspb.Message.getWrapperField(this, proto.ecommerce.orders.OrderSummary, 2));
};


/**
 * @param {?proto.ecommerce.orders.OrderSummary|undefined} value
 * @return {!proto.ecommerce.orders.OrderConfirmed} returns this
*/
proto.ecommerce.orders.OrderConfirmed.prototype.setSummary = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ecommerce.orders.OrderConfirmed} returns this
 */
proto.ecommerce.orders.OrderConfirmed.prototype.clearSummary = function() {
  return this.setSummary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ecommerce.orders.OrderConfirmed.prototype.hasSummary = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderFailed.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderFailed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderFailed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderFailed.toObject = function(includeInstance, msg) {
  var f, obj = {
orderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
reason: jspb.Message.getFieldWithDefault(msg, 2, 0),
errorMessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderFailed}
 */
proto.ecommerce.orders.OrderFailed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderFailed;
  return proto.ecommerce.orders.OrderFailed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderFailed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderFailed}
 */
proto.ecommerce.orders.OrderFailed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderId(value);
      break;
    case 2:
      var value = /** @type {!proto.ecommerce.orders.FailureReason} */ (reader.readEnum());
      msg.setReason(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderFailed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderFailed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderFailed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderFailed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReason();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string order_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.OrderFailed.prototype.getOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderFailed} returns this
 */
proto.ecommerce.orders.OrderFailed.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional FailureReason reason = 2;
 * @return {!proto.ecommerce.orders.FailureReason}
 */
proto.ecommerce.orders.OrderFailed.prototype.getReason = function() {
  return /** @type {!proto.ecommerce.orders.FailureReason} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.ecommerce.orders.FailureReason} value
 * @return {!proto.ecommerce.orders.OrderFailed} returns this
 */
proto.ecommerce.orders.OrderFailed.prototype.setReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string error_message = 3;
 * @return {string}
 */
proto.ecommerce.orders.OrderFailed.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderFailed} returns this
 */
proto.ecommerce.orders.OrderFailed.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.Customer.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.Customer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.Customer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.Customer.toObject = function(includeInstance, msg) {
  var f, obj = {
userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
email: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.Customer}
 */
proto.ecommerce.orders.Customer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.Customer;
  return proto.ecommerce.orders.Customer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.Customer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.Customer}
 */
proto.ecommerce.orders.Customer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.Customer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.Customer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.Customer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.Customer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.Customer.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.Customer} returns this
 */
proto.ecommerce.orders.Customer.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.ecommerce.orders.Customer.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.Customer} returns this
 */
proto.ecommerce.orders.Customer.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderItem.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderItem.toObject = function(includeInstance, msg) {
  var f, obj = {
productId: jspb.Message.getFieldWithDefault(msg, 1, ""),
sku: jspb.Message.getFieldWithDefault(msg, 2, ""),
name: jspb.Message.getFieldWithDefault(msg, 3, ""),
price: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
quantity: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderItem}
 */
proto.ecommerce.orders.OrderItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderItem;
  return proto.ecommerce.orders.OrderItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderItem}
 */
proto.ecommerce.orders.OrderItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string product_id = 1;
 * @return {string}
 */
proto.ecommerce.orders.OrderItem.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderItem} returns this
 */
proto.ecommerce.orders.OrderItem.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sku = 2;
 * @return {string}
 */
proto.ecommerce.orders.OrderItem.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderItem} returns this
 */
proto.ecommerce.orders.OrderItem.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.ecommerce.orders.OrderItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.OrderItem} returns this
 */
proto.ecommerce.orders.OrderItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double price = 4;
 * @return {number}
 */
proto.ecommerce.orders.OrderItem.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.OrderItem} returns this
 */
proto.ecommerce.orders.OrderItem.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 quantity = 5;
 * @return {number}
 */
proto.ecommerce.orders.OrderItem.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.OrderItem} returns this
 */
proto.ecommerce.orders.OrderItem.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.PaymentResult.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.PaymentResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.PaymentResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.PaymentResult.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, 0),
transactionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
failureReason: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.PaymentResult}
 */
proto.ecommerce.orders.PaymentResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.PaymentResult;
  return proto.ecommerce.orders.PaymentResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.PaymentResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.PaymentResult}
 */
proto.ecommerce.orders.PaymentResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ecommerce.orders.PaymentStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailureReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.PaymentResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.PaymentResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.PaymentResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.PaymentResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getFailureReason();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional PaymentStatus status = 1;
 * @return {!proto.ecommerce.orders.PaymentStatus}
 */
proto.ecommerce.orders.PaymentResult.prototype.getStatus = function() {
  return /** @type {!proto.ecommerce.orders.PaymentStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ecommerce.orders.PaymentStatus} value
 * @return {!proto.ecommerce.orders.PaymentResult} returns this
 */
proto.ecommerce.orders.PaymentResult.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string transaction_id = 2;
 * @return {string}
 */
proto.ecommerce.orders.PaymentResult.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.PaymentResult} returns this
 */
proto.ecommerce.orders.PaymentResult.prototype.setTransactionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double amount = 3;
 * @return {number}
 */
proto.ecommerce.orders.PaymentResult.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.PaymentResult} returns this
 */
proto.ecommerce.orders.PaymentResult.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string failure_reason = 4;
 * @return {string}
 */
proto.ecommerce.orders.PaymentResult.prototype.getFailureReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ecommerce.orders.PaymentResult} returns this
 */
proto.ecommerce.orders.PaymentResult.prototype.setFailureReason = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ecommerce.orders.OrderSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.ecommerce.orders.OrderSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ecommerce.orders.OrderSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
subtotal: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
taxAmount: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
totalAmount: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ecommerce.orders.OrderSummary}
 */
proto.ecommerce.orders.OrderSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ecommerce.orders.OrderSummary;
  return proto.ecommerce.orders.OrderSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ecommerce.orders.OrderSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ecommerce.orders.OrderSummary}
 */
proto.ecommerce.orders.OrderSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSubtotal(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTaxAmount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ecommerce.orders.OrderSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ecommerce.orders.OrderSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ecommerce.orders.OrderSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ecommerce.orders.OrderSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubtotal();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getTaxAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTotalAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional double subtotal = 1;
 * @return {number}
 */
proto.ecommerce.orders.OrderSummary.prototype.getSubtotal = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.OrderSummary} returns this
 */
proto.ecommerce.orders.OrderSummary.prototype.setSubtotal = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double tax_amount = 2;
 * @return {number}
 */
proto.ecommerce.orders.OrderSummary.prototype.getTaxAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.OrderSummary} returns this
 */
proto.ecommerce.orders.OrderSummary.prototype.setTaxAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double total_amount = 3;
 * @return {number}
 */
proto.ecommerce.orders.OrderSummary.prototype.getTotalAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ecommerce.orders.OrderSummary} returns this
 */
proto.ecommerce.orders.OrderSummary.prototype.setTotalAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.ecommerce.orders.EventType = {
  ORDER_CREATED: 0,
  PAYMENT_PROCESSED: 1,
  ORDER_CONFIRMED: 2,
  ORDER_FAILED: 3
};

/**
 * @enum {number}
 */
proto.ecommerce.orders.PaymentStatus = {
  PAYMENT_PENDING: 0,
  PAYMENT_COMPLETED: 1,
  PAYMENT_FAILED: 2
};

/**
 * @enum {number}
 */
proto.ecommerce.orders.FailureReason = {
  INSUFFICIENT_INVENTORY: 0,
  PAYMENT_DECLINED: 1,
  INVALID_PRODUCT: 2,
  SYSTEM_ERROR: 3
};

goog.object.extend(exports, proto.ecommerce.orders);
