class IdempotencyStore:
    def get(self, key: str) -> tuple[int, str] | None: ...
    def save_first(self, key: str, request_hash: str, status: int, body_json: str, order_id: str) -> None: ...
    def ensure_same_payload_or_conflict(self, key: str, request_hash: str) -> None: ...
