class OrderReadRepo:
    def save_pending_snapshot(self, order_doc: dict) -> None: ...
    def get_by_id(self, order_id: str) -> dict | None: ...
    def list_by_user(self, user_id: str, page: int, limit: int) -> tuple[list[dict], int]: ...
